name: siam-2025
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
    - ${RABBITMQ_SERVER_PORT}:5672
    - ${RABBITMQ_CLIENT_PORT}:15672
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    env_file:
    - ./.env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    build:
      context: ../../src/frontend/
      dockerfile: ./docker/Dockerfile
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  bff:
    build:
      context: ../../src/backend/bff
      dockerfile: ./docker/Dockerfile
    ports:
      - ${BFF_PORT}:7777
    depends_on:
      - rabbitmq
  well-tester:
    build:
      context: ../../src/backend/well_tester
      dockerfile: ./docker/Dockerfile
    depends_on:
      - bff
    ports:
      - ${WELL_TESTER_PORT}:7778
volumes:
  rabbitmq-data:
  node_modules:
